# Generated by Django 5.2.7 on 2025-11-21 20:05

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('author', 'Author'), ('basic_user', 'Basic User')], default='basic_user', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(upload_to='category/')),
                ('front_image', models.ImageField(upload_to='category/')),
                ('behind_image', models.ImageField(upload_to='category/')),
                ('side_image', models.ImageField(upload_to='category/')),
                ('top_image', models.ImageField(upload_to='category/')),
                ('bottom_image', models.ImageField(upload_to='category/')),
                ('origin', models.CharField(choices=[('india', 'Indian'), ('foreign', 'Foreign')], default='india', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='author_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('author_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('cover_image', models.ImageField(upload_to='author/')),
                ('front_image', models.ImageField(upload_to='author/')),
                ('behind_image', models.ImageField(upload_to='author/')),
                ('side_image', models.ImageField(upload_to='author/')),
                ('top_image', models.ImageField(upload_to='author/')),
                ('bottom_image', models.ImageField(upload_to='author/')),
                ('biography', models.TextField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('register_date', models.DateField(auto_now_add=True)),
                ('date_of_Birth', models.DateField()),
                ('short_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BasicUserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='basic_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('cover_image', models.ImageField(upload_to='books/')),
                ('front_image', models.ImageField(upload_to='books/')),
                ('behind_image', models.ImageField(upload_to='books/')),
                ('side_image', models.ImageField(upload_to='books/')),
                ('top_image', models.ImageField(upload_to='books/')),
                ('bottom_image', models.ImageField(upload_to='books/')),
                ('total_pages', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('isbn', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('ratings', models.DecimalField(blank=True, decimal_places=1, max_digits=2, max_length=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, max_length=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('discount', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('publications', models.CharField(blank=True, default='Anwar Publications', max_length=100, null=True)),
                ('availablity', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('maintenance', 'Under Maintenance'), ('pending', 'Pending for Approval')], default='pending', max_length=20)),
                ('language', models.CharField(choices=[('hindi', 'Hindi'), ('urdu', 'Urdu'), ('english', 'English')], default='hindi', max_length=20)),
                ('binding_types', models.CharField(choices=[('hardcover', 'Hardcover'), ('softcover', 'Softcover/Papercover'), ('stiching', 'Stiching'), ('spiral', 'Spiral')], default='softcover', max_length=20)),
                ('edition', models.CharField(choices=[('limited', 'Limited'), ('bulk', 'Bulk'), ('special', 'Special')], default='bulk', max_length=20)),
                ('description', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_of_author', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_of_books', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'books')},
            },
        ),
    ]
