# Generated by Django 5.2.7 on 2025-11-05 14:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('biography', models.TextField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('register_date', models.DateField(auto_now_add=True)),
                ('contact', models.CharField(max_length=10)),
                ('date_of_Birth', models.DateField()),
                ('short_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('origin', models.CharField(choices=[('india', 'Indian'), ('foreign', 'Foreign')], default='india', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='author/')),
                ('image_type', models.CharField(choices=[('cover', 'Cover'), ('front', 'Front'), ('behind', 'Behind'), ('top', 'Top'), ('bottom', 'Bottom'), ('side', '  Side')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_images', to='api.author')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('total_pages', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('isbn', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('ratings', models.DecimalField(blank=True, decimal_places=1, max_digits=2, max_length=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, max_length=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('discount', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('publications', models.CharField(blank=True, default='Anwar Publications', max_length=100, null=True)),
                ('availablity', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('maintenance', 'Under Maintenance'), ('pending', 'Pending for Approval')], default='pending', max_length=20)),
                ('language', models.CharField(choices=[('hindi', 'Hindi'), ('urdu', 'Urdu'), ('english', 'English')], default='hindi', max_length=20)),
                ('binding_types', models.CharField(choices=[('hardcover', 'Hardcover'), ('softcover', 'Softcover/Papercover'), ('stiching', 'Stiching'), ('spiral', 'Spiral')], default='softcover', max_length=20)),
                ('edition', models.CharField(choices=[('limited', 'Limited'), ('bulk', 'Bulk'), ('special', 'Special')], default='bulk', max_length=20)),
                ('description', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_of_author', to='api.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_of_books', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='BooksImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books/')),
                ('image_type', models.CharField(choices=[('cover', 'Cover'), ('front', 'Front'), ('behind', 'Behind'), ('top', 'Top'), ('bottom', 'Bottom'), ('side', '  Side')], max_length=20)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_images', to='api.books')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='category/')),
                ('image_type', models.CharField(choices=[('cover', 'Cover'), ('front', 'Front'), ('behind', 'Behind'), ('top', 'Top'), ('bottom', 'Bottom'), ('side', '  Side')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_images', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'books')},
            },
        ),
    ]
