# Generated by Django 5.2.7 on 2025-10-19 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, max_length=3, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
