# Generated by Django 5.2.7 on 2025-10-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_books_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
