# Generated by Django 5.2.7 on 2025-11-02 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cartlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartlist',
            name='products',
        ),
    ]
