# Generated by Django 5.2.3 on 2025-12-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='is_verified',
            new_name='is_used',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='channel',
        ),
        migrations.AddField(
            model_name='otp',
            name='otp_via',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS/Text Message')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(default='registration', max_length=30),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(max_length=128),
        ),
    ]
