# Generated by Django 5.2.7 on 2025-11-03 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cart_cart_lists_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_lists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_lists', to='api.cartlist'),
        ),
    ]
