# Generated by Django 5.2.3 on 2025-12-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_is_verified_otp_is_used_remove_otp_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_via',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS/Text Message')], default='email', max_length=10),
        ),
    ]
