# Generated by Django 5.2.7 on 2025-11-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cart_cart_lists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_lists',
        ),
    ]
