# Generated by Django 5.2.7 on 2025-11-03 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cartlist_cart_items_alter_cartlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='cart_items',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.cart'),
        ),
    ]
