# Generated by Django 5.2.7 on 2025-11-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_cartlist_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartlist',
            name='cart_items',
        ),
    ]
